### ISSUE TITLE
Missing static data in SystemModule.py

### ISSUE THREAD

**Issue by TracyMcBean** [machism0/non-bonded-periodic#3]
Calculation of the neighbour list needs following variables from SystemInfo: 

- sigma

- cutoff radius

How is the box dimension represented?

Proposel for cutoff radius:

`
     def set_cutoff_radius(self, sigma):
      
            # sigma * 2.5 is a standard approximation
            self.__cutoff_radius = sigma * 2.5

            return self.__cutoff_radius
`

**Comment by iamluvi** [comment]
Reopen the issue if needed!
