### ISSUE TITLE
Missing Variables in SystemInfo in SystemModule.py

### ISSUE THREAD

**Issue by TracyMcBean** [machism0/non-bonded-periodic#5]
1. Sigma should be added as a public variable or a method is needed to access it.

2. Calling the particle number is somewhat complicated and it would be easier if it was directly an accessible variable. 
This is how the class neighbour calls it right now:
 `__particle_number = System.state().positions().shape[0]`

**Comment by TracyMcBean** [comment]
What is sigma?

**Comment by iamluvi** [comment]
I was looking at the pdf with the project assignment and as a parameter is passed this lj_sigma, isn't this the one who would be used for the cut off radius..? There's maybe a case of homonymy, if it's so then we could have solved the Sigma Problem.
