### ISSUE TITLE
sigma

### ISSUE THREAD

**Issue by bkmi** [machism0/non-bonded-periodic#8]
we need a max sigma and a sigma for every interaction.

Check lennard-jones defs

**Comment by iamluvi** [comment]
COPYPASTE of same reply on different issue: I was looking at the pdf with the project assignment and as a parameter is passed this lj_sigma, isn't this the one who would be used for the cut off radius..?

**Comment by bkmi** [comment]
there is a sigma for every interaction. We need an array or matrix we can query when calculating potential, energy, forces.

The sigma which is used to calculate the cutoff radius is the one which results in the largest cutoff radius.

**Comment by TracyMcBean** [comment]
This is solved because the worse_sigma was added.
